# funding.yml
funding:
  - type: "github"
    url: "https://github.com/sponsors/ismail5626"
    platform: "GitHub Sponsors"
    description: "Support the development of this project directly via GitHub Sponsors."




