services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    networks:
      - network1

  # db is is db folder
  db:
    build: db/.
    ports:
      - "3306:3306"
    networks:
      - network1
    command: --default-authentication-plugin=mysql_native_password
    restart: always

networks:
  network1:
    driver: bridge