@startuml

actor DA as "Data Analyst"

rectangle Database

rectangle "Data Analysis System" {
    usecase UC4 as "Get population
    in cities + out of cities"

    usecase UCa as "Print populations"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml