name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge iaaa-methods
          docker pull mongo
          docker run -d --name mongo-dbserver --network iaaa-methods mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t iaaa_methods .
      - name: Run image
        run: docker run --network iaaa-methods --name iaaacontainer iaaa_methods
      - name: view logs
        run: docker logs iaaacontainer
